// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qlyiwvahdbpzhetadrtz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFseWl3dmFoZGJwemhldGFkcnR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MDA1MDAsImV4cCI6MjA2NDI3NjUwMH0.ai77Tq1h1RdGROU_y60MduCllHAvFX4vkGUxsnrAYiA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);